#!/bin/bash

# Test the /extract-skills API endpoint

curl -X POST http://localhost:8000/extract-skills \
  -H "Content-Type: application/json" \
  -d '{
    "text": "ANJAN YELLE Full Stack Developer | React.js Developer PROFESSIONAL SUMMARY Experienced Full Stack Developer with 4 years of experience in designing, developing, and maintaining scalable web applications. Strong expertise in React.js, JavaScript, TypeScript, Redux, Next.js, HTML5, CSS3, Tailwind CSS, Bootstrap, Node.js, Express.js, Java, Spring Boot, REST APIs, MySQL, MongoDB, AWS, Docker, Kubernetes, Git, GitHub, Jenkins, CI/CD, Agile, Scrum, and Software Development Life Cycle (SDLC). TECHNICAL SKILLS Frontend: React.js, Next.js, JavaScript, TypeScript, Redux, HTML5, CSS3, Tailwind CSS, Bootstrap, Material UI Backend: Node.js, Express.js, Java, Spring Boot Databases: MySQL, PostgreSQL, MongoDB Cloud & DevOps: AWS, Docker, Kubernetes, Jenkins, GitHub Actions, CI/CD Testing: Jest, Cypress, Selenium, Postman Version Control: Git, GitHub, GitLab Methodologies: Agile, Scrum, SDLC WORK EXPERIENCE Senior React Developer Developed enterprise-level web applications using React.js, Redux, TypeScript, and Next.js. Implemented responsive user interfaces using HTML5, CSS3, Bootstrap, Tailwind CSS, and Material UI. Integrated REST APIs and GraphQL APIs with frontend applications. Worked with Node.js and Express.js backend services. Created reusable React Hooks and custom hooks. Implemented authentication using JWT and OAuth. Optimized application performance using React.memo, useMemo, and useCallback. Configured CI/CD pipelines using Jenkins and GitHub Actions. Deployed applications on AWS using Docker and Kubernetes. Collaborated with Agile Scrum teams using Jira. PROJECTS CRM Application Technologies: React.js, Redux, TypeScript, Node.js, Express.js, MongoDB, AWS Built customer management modules. Implemented role-based access control (RBAC). Created dashboards and analytics reports. Timesheet Management System Technologies: React Native, Expo, React.js, Node.js, MySQL Developed mobile and web applications. Integrated REST APIs. Implemented employee attendance tracking. Resume Parser ATS System Technologies: Python, FastAPI, NLP, OCR, AWS Textract, OpenAI, PostgreSQL Extracted candidate information from resumes. Implemented skill extraction and matching algorithms. Built ATS score calculation engine. CERTIFICATIONS AWS Certified Cloud Practitioner React Professional Certification Java Full Stack Development Certification EDUCATION Bachelor of Technology in Computer Science Engineering SOFT SKILLS Communication, Leadership, Problem Solving, Team Collaboration, Time Management, Analytical Thinking"
  }' | jq .
