#!/usr/bin/env python3
"""
TASK 2 - Expand NER Training Data to 500+ Samples
"""

import spacy
import json
import os
from spacy.training import offsets_to_biluo_tags

def make_example(text, entity_text, label):
    """Make training example with char_span for spaCy 3.x"""
    start = text.find(entity_text)
    if start == -1:
        return None, f"entity '{entity_text}' not found in text"
    
    end = start + len(entity_text)
    doc = spacy.blank("en").make_doc(text)
    
    # Use char_span with alignment_mode="expand" for spaCy 3.x
    span = doc.char_span(start, end, label=label, alignment_mode="expand")
    
    if span is None:
        return None, f"span not alignable for '{entity_text}' in '{text}'"
    
    return (text, {"entities": [(span.start_char, span.end_char, label)]}), None

def generate_expanded_ner_training():
    """Generate 500+ NER training samples with variations"""
    
    print("🔧 TASK 2 - GENERATING 500+ NER TRAINING SAMPLES (EXPANDED)")
    print("=" * 60)
    
    # Expanded TITLE examples (200) - More variations
    title_examples = [
        # Data Analyst variations
        ("Working as Senior Data Analyst", "Senior Data Analyst", "TITLE"),
        ("Hired as Sr Data Analyst", "Sr Data Analyst", "TITLE"),
        ("Title is Sr. Data Analyst", "Sr. Data Analyst", "TITLE"),
        ("Position of Principal Data Analyst", "Principal Data Analyst", "TITLE"),
        ("Role of Lead Data Analyst", "Lead Data Analyst", "TITLE"),
        ("Analytics Lead position", "Analytics Lead", "TITLE"),
        ("Data Analyst internship", "Data Analyst", "TITLE"),
        ("Business Data Analyst role", "Business Data Analyst", "TITLE"),
        ("Senior Business Analyst", "Senior Business Analyst", "TITLE"),
        ("Sr Business Analyst position", "Sr Business Analyst", "TITLE"),
        ("Principal Business Analyst", "Principal Business Analyst", "TITLE"),
        
        # Developer variations
        ("Senior Java Developer", "Senior Java Developer", "TITLE"),
        ("Sr Java Developer", "Sr Java Developer", "TITLE"),
        ("Sr. Java Developer", "Sr. Java Developer", "TITLE"),
        ("Java Full Stack Developer", "Java Full Stack Developer", "TITLE"),
        ("Senior Full Stack Developer", "Senior Full Stack Developer", "TITLE"),
        ("Sr Full Stack Developer", "Sr Full Stack Developer", "TITLE"),
        ("Lead Java Developer", "Lead Java Developer", "TITLE"),
        ("Principal Java Developer", "Principal Java Developer", "TITLE"),
        ("Java Backend Developer", "Java Backend Developer", "TITLE"),
        ("Senior Backend Developer", "Senior Backend Developer", "TITLE"),
        ("Frontend Developer position", "Frontend Developer", "TITLE"),
        ("Senior Frontend Developer", "Senior Frontend Developer", "TITLE"),
        
        # ML Engineer variations
        ("Machine Learning Engineer", "Machine Learning Engineer", "TITLE"),
        ("ML Engineer position", "ML Engineer", "TITLE"),
        ("ML Eng role", "ML Eng", "TITLE"),
        ("Senior ML Engineer", "Senior ML Engineer", "TITLE"),
        ("Sr ML Engineer", "Sr ML Engineer", "TITLE"),
        ("Lead ML Engineer", "Lead ML Engineer", "TITLE"),
        ("Principal ML Engineer", "Principal ML Engineer", "TITLE"),
        ("Machine Learning Developer", "Machine Learning Developer", "TITLE"),
        ("AI Engineer position", "AI Engineer", "TITLE"),
        ("Senior AI Engineer", "Senior AI Engineer", "TITLE"),
        
        # Other variations
        ("Software Engineer", "Software Engineer", "TITLE"),
        ("Senior Software Engineer", "Senior Software Engineer", "TITLE"),
        ("Sr Software Engineer", "Sr Software Engineer", "TITLE"),
        ("Lead Software Engineer", "Lead Software Engineer", "TITLE"),
        ("Principal Software Engineer", "Principal Software Engineer", "TITLE"),
        ("DevOps Engineer", "DevOps Engineer", "TITLE"),
        ("Senior DevOps Engineer", "Senior DevOps Engineer", "TITLE"),
        ("Data Scientist", "Data Scientist", "TITLE"),
        ("Senior Data Scientist", "Senior Data Scientist", "TITLE"),
        ("Sr Data Scientist", "Sr Data Scientist", "TITLE"),
        ("Product Manager", "Product Manager", "TITLE"),
        ("Senior Product Manager", "Senior Product Manager", "TITLE"),
        ("Technical Lead", "Technical Lead", "TITLE"),
        ("Solutions Architect", "Solutions Architect", "TITLE"),
        ("Cloud Architect", "Cloud Architect", "TITLE"),
        ("Security Engineer", "Security Engineer", "TITLE"),
        ("QA Engineer", "QA Engineer", "TITLE"),
        ("Database Administrator", "Database Administrator", "TITLE"),
        ("System Administrator", "System Administrator", "TITLE"),
        ("Network Engineer", "Network Engineer", "TITLE"),
        ("Mobile Developer", "Mobile Developer", "TITLE"),
        ("UI/UX Designer", "UI/UX Designer", "TITLE"),
        ("Project Manager", "Project Manager", "TITLE"),
        ("Scrum Master", "Scrum Master", "TITLE"),
        ("Business Analyst", "Business Analyst", "TITLE"),
        ("Data Engineer", "Data Engineer", "TITLE"),
        ("Senior Data Engineer", "Senior Data Engineer", "TITLE"),
        ("Big Data Engineer", "Big Data Engineer", "TITLE"),
        ("Data Platform Engineer", "Data Platform Engineer", "TITLE"),
        ("Analytics Engineer", "Analytics Engineer", "TITLE"),
        ("Research Scientist", "Research Scientist", "TITLE"),
        ("Software Architect", "Software Architect", "TITLE"),
        ("Enterprise Architect", "Enterprise Architect", "TITLE"),
        ("Technical Architect", "Technical Architect", "TITLE"),
        ("Infrastructure Engineer", "Infrastructure Engineer", "TITLE"),
        ("Platform Engineer", "Platform Engineer", "TITLE"),
        ("Site Reliability Engineer", "Site Reliability Engineer", "TITLE"),
        ("Full Stack Engineer", "Full Stack Engineer", "TITLE"),
        ("Backend Engineer", "Backend Engineer", "TITLE"),
        ("Frontend Engineer", "Frontend Engineer", "TITLE"),
        ("Test Engineer", "Test Engineer", "TITLE"),
        ("Automation Engineer", "Automation Engineer", "TITLE"),
        ("Performance Engineer", "Performance Engineer", "TITLE"),
        ("Quality Engineer", "Quality Engineer", "TITLE"),
        ("Release Engineer", "Release Engineer", "TITLE"),
        ("Build Engineer", "Build Engineer", "TITLE"),
        ("Configuration Engineer", "Configuration Engineer", "TITLE"),
        ("Integration Engineer", "Integration Engineer", "TITLE"),
        ("Solutions Consultant", "Solutions Consultant", "TITLE"),
        ("Technical Consultant", "Technical Consultant", "TITLE"),
        ("Systems Analyst", "Systems Analyst", "TITLE"),
        ("IT Manager", "IT Manager", "TITLE"),
        ("Engineering Manager", "Engineering Manager", "TITLE"),
        ("Director of Engineering", "Director of Engineering", "TITLE"),
        ("VP of Engineering", "VP of Engineering", "TITLE"),
        ("CTO", "CTO", "TITLE"),
        ("Chief Technology Officer", "Chief Technology Officer", "TITLE"),
        ("Chief Architect", "Chief Architect", "TITLE"),
        ("Chief Data Officer", "Chief Data Officer", "TITLE"),
        ("Data Manager", "Data Manager", "TITLE"),
        ("Analytics Manager", "Analytics Manager", "TITLE"),
        ("BI Manager", "BI Manager", "TITLE"),
        ("Reporting Manager", "Reporting Manager", "TITLE"),
        ("Team Lead", "Team Lead", "TITLE"),
        ("Tech Lead", "Tech Lead", "TITLE"),
        ("Engineering Lead", "Engineering Lead", "TITLE"),
        ("Development Lead", "Development Lead", "TITLE"),
        ("Product Lead", "Product Lead", "TITLE"),
        ("Program Manager", "Program Manager", "TITLE"),
        ("Program Director", "Program Director", "TITLE"),
        ("Delivery Manager", "Delivery Manager", "TITLE"),
        ("Client Manager", "Client Manager", "TITLE"),
        ("Account Manager", "Account Manager", "TITLE"),
        ("Sales Engineer", "Sales Engineer", "TITLE"),
        ("Pre-sales Engineer", "Pre-sales Engineer", "TITLE"),
        ("Field Engineer", "Field Engineer", "TITLE"),
        ("Support Engineer", "Support Engineer", "TITLE"),
        ("Maintenance Engineer", "Maintenance Engineer", "TITLE"),
        ("Operations Engineer", "Operations Engineer", "TITLE"),
        ("Cloud Engineer", "Cloud Engineer", "TITLE"),
        ("Security Architect", "Security Architect", "TITLE"),
        ("Network Architect", "Network Architect", "TITLE"),
        ("Data Architect", "Data Architect", "TITLE"),
        ("ML Architect", "ML Architect", "TITLE"),
        ("AI Architect", "AI Architect", "TITLE"),
        ("Solutions Developer", "Solutions Developer", "TITLE"),
        ("Enterprise Developer", "Enterprise Developer", "TITLE"),
        ("Core Developer", "Core Developer", "TITLE"),
        ("Platform Developer", "Platform Developer", "TITLE"),
        ("Application Developer", "Application Developer", "TITLE"),
        ("Web Developer", "Web Developer", "TITLE"),
        ("Mobile App Developer", "Mobile App Developer", "TITLE"),
        ("iOS Developer", "iOS Developer", "TITLE"),
        ("Android Developer", "Android Developer", "TITLE"),
        ("React Developer", "React Developer", "TITLE"),
        ("Angular Developer", "Angular Developer", "TITLE"),
        ("Vue Developer", "Vue Developer", "TITLE"),
        ("Node Developer", "Node Developer", "TITLE"),
        ("Python Developer", "Python Developer", "TITLE"),
        ("Java Developer", "Java Developer", "TITLE"),
        ("C# Developer", "C# Developer", "TITLE"),
        ("C++ Developer", "C++ Developer", "TITLE"),
        ("Go Developer", "Go Developer", "TITLE"),
        ("Ruby Developer", "Ruby Developer", "TITLE"),
        ("PHP Developer", "PHP Developer", "TITLE"),
        ("Scala Developer", "Scala Developer", "TITLE"),
        ("Kotlin Developer", "Kotlin Developer", "TITLE"),
        ("Swift Developer", "Swift Developer", "TITLE"),
        ("TypeScript Developer", "TypeScript Developer", "TITLE"),
        ("JavaScript Developer", "JavaScript Developer", "TITLE"),
        ("Full Stack Developer", "Full Stack Developer", "TITLE"),
        ("Senior Full Stack Developer", "Senior Full Stack Developer", "TITLE"),
        ("Lead Full Stack Developer", "Lead Full Stack Developer", "TITLE"),
        ("Principal Full Stack Developer", "Principal Full Stack Developer", "TITLE"),
    ]
    
    # Expanded COMPANY examples (150) - More companies
    company_examples = [
        # Tech companies
        ("Worked at Google", "Google", "COMPANY"),
        ("Employed by Microsoft", "Microsoft", "COMPANY"),
        ("Job at Amazon", "Amazon", "COMPANY"),
        ("Position at Apple", "Apple", "COMPANY"),
        ("Role at Facebook", "Facebook", "COMPANY"),
        ("Experience at Netflix", "Netflix", "COMPANY"),
        ("Work at IBM", "IBM", "COMPANY"),
        ("Job at Oracle", "Oracle", "COMPANY"),
        ("Position at Cisco", "Cisco", "COMPANY"),
        ("Role at Intel", "Intel", "COMPANY"),
        ("Experience at NVIDIA", "NVIDIA", "COMPANY"),
        ("Work at Salesforce", "Salesforce", "COMPANY"),
        ("Job at Adobe", "Adobe", "COMPANY"),
        ("Position at Twitter", "Twitter", "COMPANY"),
        ("Role at LinkedIn", "LinkedIn", "COMPANY"),
        ("Experience at Uber", "Uber", "COMPANY"),
        ("Work at Airbnb", "Airbnb", "COMPANY"),
        ("Job at Spotify", "Spotify", "COMPANY"),
        ("Position at Slack", "Slack", "COMPANY"),
        ("Role at Zoom", "Zoom", "COMPANY"),
        ("Experience at Dropbox", "Dropbox", "COMPANY"),
        ("Work at GitHub", "GitHub", "COMPANY"),
        ("Job at GitLab", "GitLab", "COMPANY"),
        ("Position at Docker", "Docker", "COMPANY"),
        ("Experience at RedHat", "RedHat", "COMPANY"),
        ("Work at VMware", "VMware", "COMPANY"),
        ("Job at Citrix", "Citrix", "COMPANY"),
        ("Position at Palantir", "Palantir", "COMPANY"),
        
        # Consulting/Service companies
        ("Work at Accenture", "Accenture", "COMPANY"),
        ("Job at Deloitte", "Deloitte", "COMPANY"),
        ("Position at PwC", "PwC", "COMPANY"),
        ("Role at KPMG", "KPMG", "COMPANY"),
        ("Experience at EY", "EY", "COMPANY"),
        ("Work at Capgemini", "Capgemini", "COMPANY"),
        ("Job at Infosys", "Infosys", "COMPANY"),
        ("Position at TCS", "TCS", "COMPANY"),
        ("Role at Wipro", "Wipro", "COMPANY"),
        ("Experience at HCL", "HCL", "COMPANY"),
        ("Work at Cognizant", "Cognizant", "COMPANY"),
        ("Job at Tech Mahindra", "Tech Mahindra", "COMPANY"),
        ("Position at HCLTech", "HCLTech", "COMPANY"),
        ("Role at LTI", "LTI", "COMPANY"),
        ("Experience at Mphasis", "Mphasis", "COMPANY"),
        
        # Finance/Banking
        ("Work at JPMorgan Chase", "JPMorgan Chase", "COMPANY"),
        ("Job at Goldman Sachs", "Goldman Sachs", "COMPANY"),
        ("Position at Bank of America", "Bank of America", "COMPANY"),
        ("Role at Wells Fargo", "Wells Fargo", "COMPANY"),
        ("Experience at Citibank", "Citibank", "COMPANY"),
        ("Work at Morgan Stanley", "Morgan Stanley", "COMPANY"),
        ("Job at Barclays", "Barclays", "COMPANY"),
        ("Position at HSBC", "HSBC", "COMPANY"),
        
        # Retail/Consumer
        ("Work at Walmart", "Walmart", "COMPANY"),
        ("Job at Target", "Target", "COMPANY"),
        ("Position at Home Depot", "Home Depot", "COMPANY"),
        ("Role at Lowe's", "Lowe's", "COMPANY"),
        ("Experience at Starbucks", "Starbucks", "COMPANY"),
        ("Work at McDonald's", "McDonald's", "COMPANY"),
        ("Job at Coca-Cola", "Coca-Cola", "COMPANY"),
        ("Position at PepsiCo", "PepsiCo", "COMPANY"),
        
        # Healthcare
        ("Work at UnitedHealth", "UnitedHealth", "COMPANY"),
        ("Job at Pfizer", "Pfizer", "COMPANY"),
        ("Position at Johnson & Johnson", "Johnson & Johnson", "COMPANY"),
        ("Role at Merck", "Merck", "COMPANY"),
        ("Experience at Roche", "Roche", "COMPANY"),
        
        # Automotive
        ("Work at Tesla", "Tesla", "COMPANY"),
        ("Job at Ford", "Ford", "COMPANY"),
        ("Position at GM", "GM", "COMPANY"),
        ("Role at Toyota", "Toyota", "COMPANY"),
        ("Experience at Honda", "Honda", "COMPANY"),
        
        # Telecom
        ("Work at AT&T", "AT&T", "COMPANY"),
        ("Job at Verizon", "Verizon", "COMPANY"),
        ("Position at T-Mobile", "T-Mobile", "COMPANY"),
        ("Role at Sprint", "Sprint", "COMPANY"),
        ("Experience at Comcast", "Comcast", "COMPANY"),
        
        # Energy
        ("Work at ExxonMobil", "ExxonMobil", "COMPANY"),
        ("Job at Chevron", "Chevron", "COMPANY"),
        ("Position at Shell", "Shell", "COMPANY"),
        ("Role at BP", "BP", "COMPANY"),
        ("Experience at ConocoPhillips", "ConocoPhillips", "COMPANY"),
        
        # Manufacturing
        ("Work at GE", "GE", "COMPANY"),
        ("Job at Boeing", "Boeing", "COMPANY"),
        ("Position at Lockheed Martin", "Lockheed Martin", "COMPANY"),
        ("Role at Raytheon", "Raytheon", "COMPANY"),
        ("Experience at Northrop Grumman", "Northrop Grumman", "COMPANY"),
        
        # CLIENT: format examples (50)
        ("CLIENT Home Depot", "Home Depot", "COMPANY"),
        ("CLIENT Huntington Bank", "Huntington Bank", "COMPANY"),
        ("CLIENT Walgreens", "Walgreens", "COMPANY"),
        ("CLIENT T-Mobile", "T-Mobile", "COMPANY"),
        ("CLIENT Ceva Logistics", "Ceva Logistics", "COMPANY"),
        ("CLIENT Bank of America", "Bank of America", "COMPANY"),
        ("CLIENT Starbucks", "Starbucks", "COMPANY"),
        ("CLIENT Amazon", "Amazon", "COMPANY"),
        ("CLIENT Google", "Google", "COMPANY"),
        ("CLIENT Microsoft", "Microsoft", "COMPANY"),
        ("CLIENT Apple", "Apple", "COMPANY"),
        ("CLIENT Facebook", "Facebook", "COMPANY"),
        ("CLIENT Netflix", "Netflix", "COMPANY"),
        ("CLIENT IBM", "IBM", "COMPANY"),
        ("CLIENT Oracle", "Oracle", "COMPANY"),
        ("CLIENT Cisco", "Cisco", "COMPANY"),
        ("CLIENT Intel", "Intel", "COMPANY"),
        ("CLIENT NVIDIA", "NVIDIA", "COMPANY"),
        ("CLIENT Salesforce", "Salesforce", "COMPANY"),
        ("CLIENT Adobe", "Adobe", "COMPANY"),
        ("CLIENT Twitter", "Twitter", "COMPANY"),
        ("CLIENT LinkedIn", "LinkedIn", "COMPANY"),
        ("CLIENT Uber", "Uber", "COMPANY"),
        ("CLIENT Airbnb", "Airbnb", "COMPANY"),
        ("CLIENT Spotify", "Spotify", "COMPANY"),
        ("CLIENT Slack", "Slack", "COMPANY"),
        ("CLIENT Zoom", "Zoom", "COMPANY"),
        ("CLIENT Dropbox", "Dropbox", "COMPANY"),
        ("CLIENT GitHub", "GitHub", "COMPANY"),
        ("CLIENT GitLab", "GitLab", "COMPANY"),
        ("CLIENT Docker", "Docker", "COMPANY"),
        ("CLIENT VMware", "VMware", "COMPANY"),
        ("CLIENT Citrix", "Citrix", "COMPANY"),
        ("CLIENT Palantir", "Palantir", "COMPANY"),
        ("CLIENT Accenture", "Accenture", "COMPANY"),
        ("CLIENT Deloitte", "Deloitte", "COMPANY"),
        ("CLIENT PwC", "PwC", "COMPANY"),
        ("CLIENT KPMG", "KPMG", "COMPANY"),
        ("CLIENT EY", "EY", "COMPANY"),
        ("CLIENT Infosys", "Infosys", "COMPANY"),
        ("CLIENT TCS", "TCS", "COMPANY"),
        ("CLIENT Wipro", "Wipro", "COMPANY"),
        ("CLIENT HCL", "HCL", "COMPANY"),
        ("CLIENT Cognizant", "Cognizant", "COMPANY"),
        ("CLIENT Capgemini", "Capgemini", "COMPANY"),
        ("CLIENT Tech Mahindra", "Tech Mahindra", "COMPANY"),
        ("CLIENT HCLTech", "HCLTech", "COMPANY"),
    ]
    
    # Expanded DATE examples (100) - More date formats
    date_examples = [
        # Standard formats
        ("Worked from January 2020 to December 2022", "January 2020", "DATE"),
        ("Worked from January 2020 to December 2022", "December 2022", "DATE"),
        ("June 2023 to Present", "June 2023", "DATE"),
        ("June 2023 to Present", "Present", "DATE"),
        ("2020 – 2023", "2020", "DATE"),
        ("2020 – 2023", "2023", "DATE"),
        ("August 2020 – May 2023", "August 2020", "DATE"),
        ("August 2020 – May 2023", "May 2023", "DATE"),
        ("2018 - Current", "2018", "DATE"),
        ("2018 - Current", "Current", "DATE"),
        ("2017 to 2020", "2017", "DATE"),
        ("2017 to 2020", "2020", "DATE"),
        
        # Month variations
        ("Started in Jan 2020", "Jan 2020", "DATE"),
        ("Left in Dec 2022", "Dec 2022", "DATE"),
        ("From Feb 2018", "Feb 2018", "DATE"),
        ("Until Mar 2021", "Mar 2021", "DATE"),
        ("Joined Apr 2019", "Apr 2019", "DATE"),
        ("Resigned May 2023", "May 2023", "DATE"),
        ("Began Jun 2020", "Jun 2020", "DATE"),
        ("Completed Jul 2022", "Jul 2022", "DATE"),
        ("Started Aug 2021", "Aug 2021", "DATE"),
        ("Finished Sep 2023", "Sep 2023", "DATE"),
        ("Commenced Oct 2018", "Oct 2018", "DATE"),
        ("Concluded Nov 2020", "Nov 2020", "DATE"),
        
        # Year only
        ("Worked during 2019", "2019", "DATE"),
        ("Employed in 2020", "2020", "DATE"),
        ("Position in 2021", "2021", "DATE"),
        ("Role in 2022", "2022", "DATE"),
        ("Experience from 2023", "2023", "DATE"),
        
        # Range variations
        ("Period 2020-2023", "2020", "DATE"),
        ("Period 2020-2023", "2023", "DATE"),
        ("Duration 2018-2021", "2018", "DATE"),
        ("Duration 2018-2021", "2021", "DATE"),
        ("Timeframe 2019-2022", "2019", "DATE"),
        ("Timeframe 2019-2022", "2022", "DATE"),
        ("Span 2020-2023", "2020", "DATE"),
        ("Span 2020-2023", "2023", "DATE"),
        
        # Present/Current variations
        ("2020 - Present", "2020", "DATE"),
        ("2020 - Present", "Present", "DATE"),
        ("2021 - Current", "2021", "DATE"),
        ("2021 - Current", "Current", "DATE"),
        ("2022 - Ongoing", "2022", "DATE"),
        ("2022 - Ongoing", "Ongoing", "DATE"),
        ("2023 - Till date", "2023", "DATE"),
        ("2023 - Till date", "Till date", "DATE"),
        
        # Educational dates
        ("Education from 2016 to 2020", "2016", "DATE"),
        ("Education from 2016 to 2020", "2020", "DATE"),
        ("Graduated in 2019", "2019", "DATE"),
        ("Degree completed 2018", "2018", "DATE"),
        ("Batch 2017-2021", "2017", "DATE"),
        ("Batch 2017-2021", "2021", "DATE"),
        
        # Certification dates
        ("Certified in 2020", "2020", "DATE"),
        ("Certificate obtained 2021", "2021", "DATE"),
        ("Valid from 2022", "2022", "DATE"),
        ("Valid until 2025", "2025", "DATE"),
        ("Expires 2024", "2024", "DATE"),
        ("Renewed 2023", "2023", "DATE"),
        
        # More month-year combinations
        ("March 2017", "March 2017", "DATE"),
        ("April 2018", "April 2018", "DATE"),
        ("May 2019", "May 2019", "DATE"),
        ("June 2020", "June 2020", "DATE"),
        ("July 2021", "July 2021", "DATE"),
        ("August 2022", "August 2022", "DATE"),
        ("September 2023", "September 2023", "DATE"),
        ("October 2024", "October 2024", "DATE"),
        ("November 2016", "November 2016", "DATE"),
        ("December 2017", "December 2017", "DATE"),
        
        # Abbreviated months
        ("Jan 2020", "Jan 2020", "DATE"),
        ("Feb 2021", "Feb 2021", "DATE"),
        ("Mar 2022", "Mar 2022", "DATE"),
        ("Apr 2023", "Apr 2023", "DATE"),
        ("May 2019", "May 2019", "DATE"),
        ("Jun 2018", "Jun 2018", "DATE"),
        ("Jul 2017", "Jul 2017", "DATE"),
        ("Aug 2016", "Aug 2016", "DATE"),
        ("Sep 2020", "Sep 2020", "DATE"),
        ("Oct 2021", "Oct 2021", "DATE"),
        ("Nov 2022", "Nov 2022", "DATE"),
        ("Dec 2023", "Dec 2023", "DATE"),
        
        # Additional range patterns
        ("From 2020 to 2023", "2020", "DATE"),
        ("From 2020 to 2023", "2023", "DATE"),
        ("Between 2018 and 2021", "2018", "DATE"),
        ("Between 2018 and 2021", "2021", "DATE"),
        ("During 2019-2022", "2019", "DATE"),
        ("During 2019-2022", "2022", "DATE"),
        ("Throughout 2020-2023", "2020", "DATE"),
        ("Throughout 2020-2023", "2023", "DATE"),
    ]
    
    # Expanded SKILL examples (100) - More skills
    skill_examples = [
        # Programming Languages
        ("Used Python for data processing", "Python", "SKILL"),
        ("Expert in Java development", "Java", "SKILL"),
        ("Skilled in JavaScript", "JavaScript", "SKILL"),
        ("Experience with Node", "Node", "SKILL"),
        ("Knowledge of SQL", "SQL", "SKILL"),
        ("Used Redis for caching", "Redis", "SKILL"),
        ("Deployed Docker containers", "Docker", "SKILL"),
        ("Managed Kubernetes clusters", "Kubernetes", "SKILL"),
        ("Worked with AWS cloud", "AWS", "SKILL"),
        ("Built Azure pipelines", "Azure", "SKILL"),
        ("Used GCP platform", "GCP", "SKILL"),
        ("Wrote Terraform scripts", "Terraform", "SKILL"),
        ("Configured Jenkins CI", "Jenkins", "SKILL"),
        ("Used Git version control", "Git", "SKILL"),
        ("Managed Linux servers", "Linux", "SKILL"),
        ("Installed Apache web server", "Apache", "SKILL"),
        ("Configured Nginx proxy", "Nginx", "SKILL"),
        ("Used Spark big data", "Spark", "SKILL"),
        ("Worked with Hadoop", "Hadoop", "SKILL"),
        ("Used Kafka streaming", "Kafka", "SKILL"),
        ("Built Elasticsearch search", "Elasticsearch", "SKILL"),
        ("Trained TensorFlow models", "TensorFlow", "SKILL"),
        ("Used PyTorch framework", "PyTorch", "SKILL"),
        ("Applied Scikit learn", "Scikit-learn", "SKILL"),
        ("Analyzed with Pandas", "Pandas", "SKILL"),
        ("Computed with NumPy", "NumPy", "SKILL"),
        ("Created Power reports", "Power", "SKILL"),
        ("Built Tableau dashboards", "Tableau", "SKILL"),
        ("Used Excel spreadsheets", "Excel", "SKILL"),
        ("Wrote VBA macros", "VBA", "SKILL"),
        ("Programmed in Python", "Python", "SKILL"),
        ("Automated with Python", "Python", "SKILL"),
        ("Used AWS Glue", "AWS Glue", "SKILL"),
        ("Processed with PySpark", "PySpark", "SKILL"),
        ("Queried Snowflake", "Snowflake", "SKILL"),
        ("Analyzed with Databricks", "Databricks", "SKILL"),
        ("Orchestrated Airflow", "Airflow", "SKILL"),
        ("Streamed with Kafka", "Kafka", "SKILL"),
        ("Transformed with Dbt", "Dbt", "SKILL"),
        ("Automated GitHub Actions", "GitHub Actions", "SKILL"),
        ("Implemented DevOps", "DevOps", "SKILL"),
        ("Built MicroStrategy", "MicroStrategy", "SKILL"),
        ("Analyzed with Looker", "Looker", "SKILL"),
        ("Used Power BI", "Power BI", "SKILL"),
        ("Streamed with Beam", "Beam", "SKILL"),
        ("Processed with Spark", "Spark", "SKILL"),
        ("Automated Jenkins", "Jenkins", "SKILL"),
        ("Managed GitLab", "GitLab", "SKILL"),
        ("Used Bitbucket", "Bitbucket", "SKILL"),
        ("Containerized with Docker", "Docker", "SKILL"),
        ("Orchestrated Kubernetes", "Kubernetes", "SKILL"),
        ("Wrote Terraform", "Terraform", "SKILL"),
        ("Configured Ansible", "Ansible", "SKILL"),
        ("Automated with Puppet", "Puppet", "SKILL"),
        ("Used Chef", "Chef", "SKILL"),
        ("Monitored Prometheus", "Prometheus", "SKILL"),
        ("Built Grafana", "Grafana", "SKILL"),
        ("Logged with ELK", "ELK", "SKILL"),
        ("Visualized with Kibana", "Kibana", "SKILL"),
        ("Processed with Logstash", "Logstash", "SKILL"),
        ("Used React", "React", "SKILL"),
        ("Built Angular", "Angular", "SKILL"),
        ("Created Vue", "Vue", "SKILL"),
        ("Used Express", "Express", "SKILL"),
        ("Applied Spring", "Spring", "SKILL"),
        ("Built with Spring Boot", "Spring Boot", "SKILL"),
        ("Used Hibernate ORM", "Hibernate", "SKILL"),
        ("Applied Spring MVC", "Spring MVC", "SKILL"),
        ("Used Maven build", "Maven", "SKILL"),
        ("Built with Gradle", "Gradle", "SKILL"),
        ("Tested with JUnit", "JUnit", "SKILL"),
        ("Used Mockito framework", "Mockito", "SKILL"),
        ("Automated with Selenium", "Selenium", "SKILL"),
        ("Tested with Cypress", "Cypress", "SKILL"),
        ("Used Postman API", "Postman", "SKILL"),
        ("Built RabbitMQ messaging", "RabbitMQ", "SKILL"),
        ("Used IBM MQ", "IBM MQ", "SKILL"),
        ("Built Apache Beam", "Apache Beam", "SKILL"),
        ("Used Delta Lake", "Delta Lake", "SKILL"),
        ("Built Apache Iceberg", "Apache Iceberg", "SKILL"),
        ("Used Parquet format", "Parquet", "SKILL"),
        ("Processed with Hadoop", "Hadoop", "SKILL"),
        ("Used Hive queries", "Hive", "SKILL"),
        ("Streamed with Flink", "Apache Flink", "SKILL"),
        ("Used Cassandra", "Cassandra", "SKILL"),
        ("Built DynamoDB", "DynamoDB", "SKILL"),
        ("Used Elasticsearch", "Elasticsearch", "SKILL"),
        ("Monitored with Splunk", "Splunk", "SKILL"),
        ("Used Confluence docs", "Confluence", "SKILL"),
        ("Tracked with JIRA", "JIRA", "SKILL"),
        ("Followed Agile", "Agile", "SKILL"),
        ("Used Scrum", "Scrum", "SKILL"),
        ("Applied TDD", "TDD", "SKILL"),
        ("Built REST APIs", "REST API", "SKILL"),
        ("Used GraphQL", "GraphQL", "SKILL"),
        ("Implemented OAuth", "OAuth", "SKILL"),
        ("Used SonarQube", "SonarQube", "SKILL"),
        ("Processed with R", "R", "SKILL"),
        ("Used MATLAB", "MATLAB", "SKILL"),
        ("Built Keras models", "Keras", "SKILL"),
        ("Used XGBoost", "XGBoost", "SKILL"),
        ("Applied PCA", "PCA", "SKILL"),
        ("Used Random Forest", "Random Forest", "SKILL"),
        ("Built Linear Regression", "Linear Regression", "SKILL"),
        ("Applied Logistic Regression", "Logistic Regression", "SKILL"),
        ("Used Decision Trees", "Decision Trees", "SKILL"),
        ("Built Neural Networks", "Neural Networks", "SKILL"),
        ("Applied Deep Learning", "Deep Learning", "SKILL"),
        ("Used Computer Vision", "Computer Vision", "SKILL"),
        ("Applied NLP", "NLP", "SKILL"),
        ("Used Natural Language Processing", "Natural Language Processing", "SKILL"),
        ("Built Time Series", "Time Series", "SKILL"),
        ("Applied Anomaly Detection", "Anomaly Detection", "SKILL"),
        ("Used Clustering", "Clustering", "SKILL"),
        ("Applied Classification", "Classification", "SKILL"),
        ("Used Regression", "Regression", "SKILL"),
        ("Built Recommendation", "Recommendation", "SKILL"),
        ("Applied A/B Testing", "A/B Testing", "SKILL"),
        ("Used Statistical Analysis", "Statistical Analysis", "SKILL"),
        ("Applied Data Mining", "Data Mining", "SKILL"),
        ("Used Data Visualization", "Data Visualization", "SKILL"),
        ("Built Data Warehousing", "Data Warehousing", "SKILL"),
        ("Applied ETL", "ETL", "SKILL"),
        ("Used Data Pipeline", "Data Pipeline", "SKILL"),
        ("Built Data Lake", "Data Lake", "SKILL"),
        ("Applied Data Governance", "Data Governance", "SKILL"),
        ("Used Data Quality", "Data Quality", "SKILL"),
        ("Applied Master Data", "Master Data", "SKILL"),
        ("Used Reference Data", "Reference Data", "SKILL"),
        ("Built Metadata", "Metadata", "SKILL"),
        ("Applied Data Catalog", "Data Catalog", "SKILL"),
        ("Used Data Lineage", "Data Lineage", "SKILL"),
        ("Applied Data Privacy", "Data Privacy", "SKILL"),
        ("Used Data Security", "Data Security", "SKILL"),
        ("Applied Compliance", "Compliance", "SKILL"),
        ("Used GDPR", "GDPR", "SKILL"),
        ("Applied HIPAA", "HIPAA", "SKILL"),
        ("Used SOX", "SOX", "SKILL"),
        ("Applied PCI", "PCI", "SKILL"),
        ("Built Microservices", "Microservices", "SKILL"),
        ("Used Service Mesh", "Service Mesh", "SKILL"),
        ("Applied API Gateway", "API Gateway", "SKILL"),
        ("Used Load Balancer", "Load Balancer", "SKILL"),
        ("Applied Circuit Breaker", "Circuit Breaker", "SKILL"),
        ("Used Rate Limiting", "Rate Limiting", "SKILL"),
        ("Applied Caching", "Caching", "SKILL"),
        ("Used CDN", "CDN", "SKILL"),
        ("Applied CDN", "CDN", "SKILL"),
        ("Used Edge Computing", "Edge Computing", "SKILL"),
        ("Applied Serverless", "Serverless", "SKILL"),
        ("Used FaaS", "FaaS", "SKILL"),
        ("Applied Lambda", "Lambda", "SKILL"),
        ("Used Functions", "Functions", "SKILL"),
        ("Applied Event Driven", "Event Driven", "SKILL"),
        ("Used Event Sourcing", "Event Sourcing", "SKILL"),
        ("Applied CQRS", "CQRS", "SKILL"),
        ("Used Saga Pattern", "Saga Pattern", "SKILL"),
        ("Applied Distributed", "Distributed", "SKILL"),
        ("Used Microkernel", "Microkernel", "SKILL"),
        ("Applied Monolith", "Monolith", "SKILL"),
        ("Used Modular", "Modular", "SKILL"),
        ("Applied Hexagonal", "Hexagonal", "SKILL"),
        ("Used Clean Architecture", "Clean Architecture", "SKILL"),
        ("Applied DDD", "DDD", "SKILL"),
        ("Used Domain Driven Design", "Domain Driven Design", "SKILL"),
        ("Applied Bounded Context", "Bounded Context", "SKILL"),
        ("Used Aggregate Root", "Aggregate Root", "SKILL"),
        ("Applied Event Storming", "Event Storming", "SKILL"),
        ("Used Context Mapping", "Context Mapping", "SKILL"),
        ("Applied Anti Corruption", "Anti Corruption", "SKILL"),
        ("Used Shared Kernel", "Shared Kernel", "SKILL"),
        ("Applied Conformist", "Conformist", "SKILL"),
        ("Used Customer Supplier", "Customer Supplier", "SKILL"),
        ("Applied Open Host", "Open Host", "SKILL"),
        ("Used Published Language", "Published Language", "SKILL"),
        ("Applied Ubiquitous", "Ubiquitous", "SKILL"),
        ("Used Bounded Context", "Bounded Context", "SKILL"),
        ("Applied Entity", "Entity", "SKILL"),
        ("Used Value Object", "Value Object", "SKILL"),
        ("Applied Repository", "Repository", "SKILL"),
        ("Used Factory", "Factory", "SKILL"),
        ("Applied Strategy", "Strategy", "SKILL"),
        ("Used Command", "Command", "SKILL"),
        ("Applied Query", "Query", "SKILL"),
        ("Used Event", "Event", "SKILL"),
        ("Applied Aggregate", "Aggregate", "SKILL"),
    ]
    
    # Expanded EDUCATION examples (80) - More degrees
    education_examples = [
        # Bachelor degrees
        ("Completed Bachelor of Technology degree", "Bachelor of Technology", "EDUCATION"),
        ("Earned B.Tech from college", "B.Tech", "EDUCATION"),
        ("Finished Bachelor of Engineering course", "Bachelor of Engineering", "EDUCATION"),
        ("Completed B.E Computer Engineering", "B.E", "EDUCATION"),
        ("Bachelor of Science degree", "Bachelor of Science", "EDUCATION"),
        ("Earned B.Sc Computer Science", "B.Sc", "EDUCATION"),
        ("Bachelor of Arts degree", "Bachelor of Arts", "EDUCATION"),
        ("Completed B.A. Economics", "B.A", "EDUCATION"),
        ("Bachelor of Commerce degree", "Bachelor of Commerce", "EDUCATION"),
        ("Earned B.Com Accounting", "B.Com", "EDUCATION"),
        ("Bachelor of Business Administration", "Bachelor of Business Administration", "EDUCATION"),
        ("Completed BBA Marketing", "BBA", "EDUCATION"),
        ("Bachelor of Computer Applications", "Bachelor of Computer Applications", "EDUCATION"),
        ("Earned BCA Software", "BCA", "EDUCATION"),
        ("Bachelor of Information Technology", "Bachelor of Information Technology", "EDUCATION"),
        ("Completed BIT Networking", "BIT", "EDUCATION"),
        
        # Master degrees
        ("Master of Technology degree", "Master of Technology", "EDUCATION"),
        ("Earned M.Tech in CS", "M.Tech", "EDUCATION"),
        ("Master of Engineering degree", "Master of Engineering", "EDUCATION"),
        ("Completed M.E. Software", "M.E", "EDUCATION"),
        ("Master of Science degree", "Master of Science", "EDUCATION"),
        ("Earned M.Sc Data Science", "M.Sc", "EDUCATION"),
        ("Master of Arts degree", "Master of Arts", "EDUCATION"),
        ("Completed M.A. English", "M.A", "EDUCATION"),
        ("Master of Commerce degree", "Master of Commerce", "EDUCATION"),
        ("Earned M.Com Finance", "M.Com", "EDUCATION"),
        ("Master of Business Administration", "Master of Business Administration", "EDUCATION"),
        ("Completed MBA Finance", "MBA", "EDUCATION"),
        ("Master of Computer Applications", "Master of Computer Applications", "EDUCATION"),
        ("Earned MCA Systems", "MCA", "EDUCATION"),
        ("Master of Information Technology", "Master of Information Technology", "EDUCATION"),
        ("Completed MIT Security", "MIT", "EDUCATION"),
        
        # PhD degrees
        ("Doctor of Philosophy degree", "Doctor of Philosophy", "EDUCATION"),
        ("Completed Ph.D. Computer Science", "Ph.D", "EDUCATION"),
        ("PhD in Machine Learning", "PhD", "EDUCATION"),
        ("Doctor of Engineering", "Doctor of Engineering", "EDUCATION"),
        ("Doctor of Science", "Doctor of Science", "EDUCATION"),
        ("Doctor of Business Administration", "Doctor of Business Administration", "EDUCATION"),
        
        # Associate/Diploma
        ("Associate Degree completed", "Associate Degree", "EDUCATION"),
        ("Associate of Science", "Associate of Science", "EDUCATION"),
        ("Associate of Arts", "Associate of Arts", "EDUCATION"),
        ("Diploma in IT completed", "Diploma in IT", "EDUCATION"),
        ("Post Graduate Diploma", "Post Graduate Diploma", "EDUCATION"),
        ("PGD in Computer Science", "PGD", "EDUCATION"),
        ("Certificate in Data Science", "Certificate in Data Science", "EDUCATION"),
        ("Advanced Certificate", "Advanced Certificate", "EDUCATION"),
        
        # University variations
        ("Bharath University Bachelor of Technology", "Bachelor of Technology", "EDUCATION"),
        ("IIT Bombay B.Tech Computer Science", "B.Tech", "EDUCATION"),
        ("IIM Ahmedabad MBA", "MBA", "EDUCATION"),
        ("MIT Master of Science", "Master of Science", "EDUCATION"),
        ("Stanford University PhD", "PhD", "EDUCATION"),
        ("Anna University B.E", "B.E", "EDUCATION"),
        ("Osmania University M.Tech", "M.Tech", "EDUCATION"),
        ("BITS Pilani B.E", "B.E", "EDUCATION"),
        ("NIT Warangal B.Tech", "B.Tech", "EDUCATION"),
        ("VIT University M.Tech", "M.Tech", "EDUCATION"),
        ("Pune University B.E", "B.E", "EDUCATION"),
        ("JNTU Hyderabad B.Tech", "B.Tech", "EDUCATION"),
        ("Delhi University M.Sc", "M.Sc", "EDUCATION"),
        ("Mumbai University B.Com", "B.Com", "EDUCATION"),
        ("Calcutta University B.A", "B.A", "EDUCATION"),
        ("Chennai University MBA", "MBA", "EDUCATION"),
        ("Bangalore University BCA", "BCA", "EDUCATION"),
        ("Hyderabad University MCA", "MCA", "EDUCATION"),
        ("Kolkata University MIT", "MIT", "EDUCATION"),
        
        # Field-specific degrees
        ("B.Tech Computer Science", "B.Tech", "EDUCATION"),
        ("B.Tech Information Technology", "B.Tech", "EDUCATION"),
        ("B.Tech Electronics", "B.Tech", "EDUCATION"),
        ("B.Tech Mechanical", "B.Tech", "EDUCATION"),
        ("B.Tech Civil", "B.Tech", "EDUCATION"),
        ("B.Tech Electrical", "B.Tech", "EDUCATION"),
        ("B.Tech Chemical", "B.Tech", "EDUCATION"),
        ("B.E Computer Science", "B.E", "EDUCATION"),
        ("B.E Information Technology", "B.E", "EDUCATION"),
        ("B.E Electronics", "B.E", "EDUCATION"),
        ("B.E Mechanical", "B.E", "EDUCATION"),
        ("B.E Civil", "B.E", "EDUCATION"),
        ("B.E Electrical", "B.E", "EDUCATION"),
        ("B.E Chemical", "B.E", "EDUCATION"),
        ("M.Tech Computer Science", "M.Tech", "EDUCATION"),
        ("M.Tech Information Technology", "M.Tech", "EDUCATION"),
        ("M.Tech Electronics", "M.Tech", "EDUCATION"),
        ("M.Tech Mechanical", "M.Tech", "EDUCATION"),
        ("M.Tech Civil", "M.Tech", "EDUCATION"),
        ("M.Tech Electrical", "M.Tech", "EDUCATION"),
        ("M.Tech Chemical", "M.Tech", "EDUCATION"),
        ("M.E Computer Science", "M.E", "EDUCATION"),
        ("M.E Information Technology", "M.E", "EDUCATION"),
        ("M.E Electronics", "M.E", "EDUCATION"),
        ("M.E Mechanical", "M.E", "EDUCATION"),
        ("M.E Civil", "M.E", "EDUCATION"),
        ("M.E Electrical", "M.E", "EDUCATION"),
        ("M.E Chemical", "M.E", "EDUCATION"),
        
        # Professional degrees
        ("MBBS Bachelor of Medicine", "MBBS", "EDUCATION"),
        ("BDS Bachelor of Dental Surgery", "BDS", "EDUCATION"),
        ("LLB Bachelor of Laws", "LLB", "EDUCATION"),
        ("BEd Bachelor of Education", "BEd", "EDUCATION"),
        ("BPharm Bachelor of Pharmacy", "BPharm", "EDUCATION"),
        ("BArch Bachelor of Architecture", "BArch", "EDUCATION"),
        ("BDes Bachelor of Design", "BDes", "EDUCATION"),
        ("BFa Bachelor of Fine Arts", "BFa", "EDUCATION"),
        ("BCom Bachelor of Commerce", "BCom", "EDUCATION"),
        ("BA Bachelor of Arts", "BA", "EDUCATION"),
        ("BSc Bachelor of Science", "BSc", "EDUCATION"),
        ("BTech Bachelor of Technology", "BTech", "EDUCATION"),
        ("BE Bachelor of Engineering", "BE", "EDUCATION"),
        
        # International degrees
        ("Bachelor Degree", "Bachelor Degree", "EDUCATION"),
        ("Master Degree", "Master Degree", "EDUCATION"),
        ("Doctorate Degree", "Doctorate Degree", "EDUCATION"),
        ("Undergraduate Degree", "Undergraduate Degree", "EDUCATION"),
        ("Graduate Degree", "Graduate Degree", "EDUCATION"),
        ("Postgraduate Degree", "Postgraduate Degree", "EDUCATION"),
        ("Professional Degree", "Professional Degree", "EDUCATION"),
        ("Technical Degree", "Technical Degree", "EDUCATION"),
        ("Academic Degree", "Academic Degree", "EDUCATION"),
        ("Research Degree", "Research Degree", "EDUCATION"),
    ]
    
    # Expanded CERTIFICATION examples (80) - More certifications
    cert_examples = [
        # AWS certifications
        ("AWS Certified Solutions Architect", "AWS Certified Solutions Architect", "CERTIFICATION"),
        ("AWS Certified Developer Associate", "AWS Certified Developer Associate", "CERTIFICATION"),
        ("AWS Certified Data Analytics", "AWS Certified Data Analytics", "CERTIFICATION"),
        ("AWS Certified Machine Learning", "AWS Certified Machine Learning", "CERTIFICATION"),
        ("AWS Certified Cloud Practitioner", "AWS Certified Cloud Practitioner", "CERTIFICATION"),
        ("AWS Certified Security Specialty", "AWS Certified Security Specialty", "CERTIFICATION"),
        ("AWS Certified Networking Specialty", "AWS Certified Networking Specialty", "CERTIFICATION"),
        ("AWS Certified Database Specialty", "AWS Certified Database Specialty", "CERTIFICATION"),
        ("AWS Certified Big Data Specialty", "AWS Certified Big Data Specialty", "CERTIFICATION"),
        ("AWS Certified Alexa Skill Builder", "AWS Certified Alexa Skill Builder", "CERTIFICATION"),
        
        # Microsoft certifications
        ("Microsoft Certified Expert", "Microsoft Certified Expert", "CERTIFICATION"),
        ("Microsoft Certified Solutions Expert", "Microsoft Certified Solutions Expert", "CERTIFICATION"),
        ("Microsoft Certified Azure Administrator", "Microsoft Certified Azure Administrator", "CERTIFICATION"),
        ("Microsoft Certified Azure Developer", "Microsoft Certified Azure Developer", "CERTIFICATION"),
        ("Microsoft Certified Azure Data Engineer", "Microsoft Certified Azure Data Engineer", "CERTIFICATION"),
        ("Microsoft Certified Azure AI Engineer", "Microsoft Certified Azure AI Engineer", "CERTIFICATION"),
        ("Microsoft Certified Azure Fundamentals", "Microsoft Certified Azure Fundamentals", "CERTIFICATION"),
        ("Microsoft Certified Azure Security Engineer", "Microsoft Certified Azure Security Engineer", "CERTIFICATION"),
        ("Microsoft Certified DevOps Engineer", "Microsoft Certified DevOps Engineer", "CERTIFICATION"),
        ("Microsoft Certified Solutions Architect", "Microsoft Certified Solutions Architect", "CERTIFICATION"),
        
        # Google Cloud certifications
        ("Google Cloud Professional", "Google Cloud Professional", "CERTIFICATION"),
        ("Google Associate Cloud Engineer", "Google Associate Cloud Engineer", "CERTIFICATION"),
        ("Google Cloud Professional Data Engineer", "Google Cloud Professional Data Engineer", "CERTIFICATION"),
        ("Google Cloud Professional Cloud Architect", "Google Cloud Professional Cloud Architect", "CERTIFICATION"),
        ("Google Cloud Professional Network Engineer", "Google Cloud Professional Network Engineer", "CERTIFICATION"),
        ("Google Cloud Professional Security Engineer", "Google Cloud Professional Security Engineer", "CERTIFICATION"),
        ("Google Cloud Professional Collaboration Engineer", "Google Cloud Professional Collaboration Engineer", "CERTIFICATION"),
        ("Google Cloud Professional Machine Learning Engineer", "Google Cloud Professional Machine Learning Engineer", "CERTIFICATION"),
        
        # Oracle certifications
        ("Oracle Certified Professional", "Oracle Certified Professional", "CERTIFICATION"),
        ("Oracle Certified Associate", "Oracle Certified Associate", "CERTIFICATION"),
        ("Oracle Certified Master", "Oracle Certified Master", "CERTIFICATION"),
        ("Oracle Certified Expert", "Oracle Certified Expert", "CERTIFICATION"),
        ("Oracle Certified Specialist", "Oracle Certified Specialist", "CERTIFICATION"),
        ("Oracle Gen AI Certified", "Oracle Gen AI Certified", "CERTIFICATION"),
        ("Oracle Cloud Infrastructure", "Oracle Cloud Infrastructure", "CERTIFICATION"),
        ("Oracle Database Administrator", "Oracle Database Administrator", "CERTIFICATION"),
        ("Oracle Java Developer", "Oracle Java Developer", "CERTIFICATION"),
        ("Oracle PL/SQL Developer", "Oracle PL/SQL Developer", "CERTIFICATION"),
        
        # Security certifications
        ("CISSP Information Security", "CISSP Information Security", "CERTIFICATION"),
        ("CompTIA Security Plus", "CompTIA Security Plus", "CERTIFICATION"),
        ("CompTIA Network Plus", "CompTIA Network Plus", "CERTIFICATION"),
        ("CompTIA A Plus", "CompTIA A Plus", "CERTIFICATION"),
        ("CEH Certified Ethical Hacker", "CEH Certified Ethical Hacker", "CERTIFICATION"),
        ("CHFI Computer Hacking Forensic Investigator", "CHFI Computer Hacking Forensic Investigator", "CERTIFICATION"),
        ("ECSA EC-Council Certified Security Analyst", "ECSA EC-Council Certified Security Analyst", "CERTIFICATION"),
        ("LPT Licensed Penetration Tester", "LPT Licensed Penetration Tester", "CERTIFICATION"),
        
        # Project Management certifications
        ("PMP Project Management Professional", "PMP Project Management Professional", "CERTIFICATION"),
        ("PMI ACP Agile Certified Practitioner", "PMI ACP Agile Certified Practitioner", "CERTIFICATION"),
        ("PMI PMP Project Management Professional", "PMI PMP Project Management Professional", "CERTIFICATION"),
        ("PMI RMP Risk Management Professional", "PMI RMP Risk Management Professional", "CERTIFICATION"),
        ("PMI SP Scheduling Professional", "PMI SP Scheduling Professional", "CERTIFICATION"),
        ("PRINCE2 Practitioner", "PRINCE2 Practitioner", "CERTIFICATION"),
        ("PRINCE2 Foundation", "PRINCE2 Foundation", "CERTIFICATION"),
        ("AgilePM Agile Project Management", "AgilePM Agile Project Management", "CERTIFICATION"),
        ("Scrum Master Certified", "Scrum Master Certified", "CERTIFICATION"),
        ("Certified Scrum Master", "Certified Scrum Master", "CERTIFICATION"),
        ("Professional Scrum Master", "Professional Scrum Master", "CERTIFICATION"),
        ("Professional Scrum Product Owner", "Professional Scrum Product Owner", "CERTIFICATION"),
        ("SAFe Agilist", "SAFe Agilist", "CERTIFICATION"),
        ("SAFe Scrum Master", "SAFe Scrum Master", "CERTIFICATION"),
        ("SAFe Product Owner", "SAFe Product Owner", "CERTIFICATION"),
        
        # DevOps certifications
        ("Certified Kubernetes Administrator", "Certified Kubernetes Administrator", "CERTIFICATION"),
        ("Certified Kubernetes Application Developer", "Certified Kubernetes Application Developer", "CERTIFICATION"),
        ("Certified Kubernetes Security Specialist", "Certified Kubernetes Security Specialist", "CERTIFICATION"),
        ("Red Hat Certified Engineer", "Red Hat Certified Engineer", "CERTIFICATION"),
        ("Red Hat Certified System Administrator", "Red Hat Certified System Administrator", "CERTIFICATION"),
        ("Red Hat Certified Architect", "Red Hat Certified Architect", "CERTIFICATION"),
        ("Docker Certified Associate", "Docker Certified Associate", "CERTIFICATION"),
        ("Docker Certified Professional", "Docker Certified Professional", "CERTIFICATION"),
        ("Jenkins Certified Engineer", "Jenkins Certified Engineer", "CERTIFICATION"),
        ("GitLab Certified Professional", "GitLab Certified Professional", "CERTIFICATION"),
        ("GitHub Actions certification", "GitHub Actions certification", "CERTIFICATION"),
        ("HashiCorp Certified Terraform Associate", "HashiCorp Certified Terraform Associate", "CERTIFICATION"),
        ("HashiCorp Certified Vault Associate", "HashiCorp Certified Vault Associate", "CERTIFICATION"),
        ("HashiCorp Certified Consul Associate", "HashiCorp Certified Consul Associate", "CERTIFICATION"),
        ("Ansible Certified Engineer", "Ansible Certified Engineer", "CERTIFICATION"),
        ("Puppet Certified Professional", "Puppet Certified Professional", "CERTIFICATION"),
        ("Chef Certified Developer", "Chef Certified Developer", "CERTIFICATION"),
        
        # Database certifications
        ("Oracle Database Administrator", "Oracle Database Administrator", "CERTIFICATION"),
        ("MongoDB Certified Developer", "MongoDB Certified Developer", "CERTIFICATION"),
        ("MySQL Certified Database Administrator", "MySQL Certified Database Administrator", "CERTIFICATION"),
        ("PostgreSQL Certified Associate", "PostgreSQL Certified Associate", "CERTIFICATION"),
        ("Cassandra Certified Developer", "Cassandra Certified Developer", "CERTIFICATION"),
        ("Redis Certified Developer", "Redis Certified Developer", "CERTIFICATION"),
        ("Neo4j Certified Developer", "Neo4j Certified Developer", "CERTIFICATION"),
        ("Elasticsearch Certified Engineer", "Elasticsearch Certified Engineer", "CERTIFICATION"),
        ("InfluxDB Certified Developer", "InfluxDB Certified Developer", "CERTIFICATION"),
        ("SnowPro Core Certification", "SnowPro Core Certification", "CERTIFICATION"),
        ("SnowPro Advanced Certification", "SnowPro Advanced Certification", "CERTIFICATION"),
        ("Databricks Certified Associate", "Databricks Certified Associate", "CERTIFICATION"),
        ("Databricks Certified Professional", "Databricks Certified Professional", "CERTIFICATION"),
        
        # Programming certifications
        ("Java Certified Programmer", "Java Certified Programmer", "CERTIFICATION"),
        ("Oracle Java SE Programmer", "Oracle Java SE Programmer", "CERTIFICATION"),
        ("Python Certified Entry Level", "Python Certified Entry Level", "CERTIFICATION"),
        ("Microsoft Certified Python Developer", "Microsoft Certified Python Developer", "CERTIFICATION"),
        ("C++ Certified Programmer", "C++ Certified Programmer", "CERTIFICATION"),
        ("C# Certified Developer", "C# Certified Developer", "CERTIFICATION"),
        ("JavaScript Certified Developer", "JavaScript Certified Developer", "CERTIFICATION"),
        ("TypeScript Certified Developer", "TypeScript Certified Developer", "CERTIFICATION"),
        ("React Certified Developer", "React Certified Developer", "CERTIFICATION"),
        ("Angular Certified Developer", "Angular Certified Developer", "CERTIFICATION"),
        ("Vue.js Certified Developer", "Vue.js Certified Developer", "CERTIFICATION"),
        ("Node.js Certified Developer", "Node.js Certified Developer", "CERTIFICATION"),
        
        # Data Science certifications
        ("TensorFlow Developer Certificate", "TensorFlow Developer Certificate", "CERTIFICATION"),
        ("PyTorch Developer Certificate", "PyTorch Developer Certificate", "CERTIFICATION"),
        ("Scikit-learn Certified Professional", "Scikit-learn Certified Professional", "CERTIFICATION"),
        ("Data Science Certificate", "Data Science Certificate", "CERTIFICATION"),
        ("Machine Learning Certificate", "Machine Learning Certificate", "CERTIFICATION"),
        ("Deep Learning Certificate", "Deep Learning Certificate", "CERTIFICATION"),
        ("Artificial Intelligence Certificate", "Artificial Intelligence Certificate", "CERTIFICATION"),
        ("Data Engineering Certificate", "Data Engineering Certificate", "CERTIFICATION"),
        ("Big Data Certificate", "Big Data Certificate", "CERTIFICATION"),
        ("Data Analytics Certificate", "Data Analytics Certificate", "CERTIFICATION"),
        
        # Cloud certifications
        ("AWS Solutions Architect", "AWS Solutions Architect", "CERTIFICATION"),
        ("Azure Solutions Architect", "Azure Solutions Architect", "CERTIFICATION"),
        ("Google Cloud Architect", "Google Cloud Architect", "CERTIFICATION"),
        ("Cloud Security Certificate", "Cloud Security Certificate", "CERTIFICATION"),
        ("Cloud Native Certificate", "Cloud Native Certificate", "CERTIFICATION"),
        ("Multi-Cloud Certificate", "Multi-Cloud Certificate", "CERTIFICATION"),
        ("Hybrid Cloud Certificate", "Hybrid Cloud Certificate", "CERTIFICATION"),
        
        # Networking certifications
        ("Cisco Certified Network Associate", "Cisco Certified Network Associate", "CERTIFICATION"),
        ("Cisco Certified Network Professional", "Cisco Certified Network Professional", "CERTIFICATION"),
        ("Cisco Certified Internetwork Expert", "Cisco Certified Internetwork Expert", "CERTIFICATION"),
        ("Juniper Certified Network Associate", "Juniper Certified Network Associate", "CERTIFICATION"),
        ("Juniper Certified Network Professional", "Juniper Certified Network Professional", "CERTIFICATION"),
        ("CompTIA Network Plus", "CompTIA Network Plus", "CERTIFICATION"),
        ("Network Plus Certificate", "Network Plus Certificate", "CERTIFICATION"),
        
        # Additional certifications
        ("ITIL Foundation Certificate", "ITIL Foundation Certificate", "CERTIFICATION"),
        ("ITIL Intermediate Certificate", "ITIL Intermediate Certificate", "CERTIFICATION"),
        ("ITIL Expert Certificate", "ITIL Expert Certificate", "CERTIFICATION"),
        ("ITIL Master Certificate", "ITIL Master Certificate", "CERTIFICATION"),
        ("Linux Professional Institute", "Linux Professional Institute", "CERTIFICATION"),
        ("Linux Certified Administrator", "Linux Certified Administrator", "CERTIFICATION"),
        ("Linux Certified Engineer", "Linux Certified Engineer", "CERTIFICATION"),
        ("VMware Certified Professional", "VMware Certified Professional", "CERTIFICATION"),
        ("VMware Certified Advanced Professional", "VMware Certified Advanced Professional", "CERTIFICATION"),
        ("VMware Certified Design Expert", "VMware Certified Design Expert", "CERTIFICATION"),
        ("Citrix Certified Administrator", "Citrix Certified Administrator", "CERTIFICATION"),
        ("Citrix Certified Engineer", "Citrix Certified Engineer", "CERTIFICATION"),
        ("Citrix Certified Expert", "Citrix Certified Expert", "CERTIFICATION"),
        ("Splunk Certified Administrator", "Splunk Certified Administrator", "CERTIFICATION"),
        ("Splunk Certified Power User", "Splunk Certified Power User", "CERTIFICATION"),
        ("Splunk Certified Architect", "Splunk Certified Architect", "CERTIFICATION"),
        ("Tableau Desktop Specialist", "Tableau Desktop Specialist", "CERTIFICATION"),
        ("Tableau Server Certified", "Tableau Server Certified", "CERTIFICATION"),
        ("Tableau Certified Associate", "Tableau Certified Associate", "CERTIFICATION"),
        ("Tableau Certified Professional", "Tableau Certified Professional", "CERTIFICATION"),
        ("Power BI Certified", "Power BI Certified", "CERTIFICATION"),
        ("Power BI Data Analyst", "Power BI Data Analyst", "CERTIFICATION"),
        ("Power BI Developer", "Power BI Developer", "CERTIFICATION"),
        ("QlikView Certified Developer", "QlikView Certified Developer", "CERTIFICATION"),
        ("Qlik Sense Certified", "Qlik Sense Certified", "CERTIFICATION"),
        ("LookML Certified Developer", "LookML Certified Developer", "CERTIFICATION"),
        ("Looker Certified Analyst", "Looker Certified Analyst", "CERTIFICATION"),
        ("MicroStrategy Certified Developer", "MicroStrategy Certified Developer", "CERTIFICATION"),
        ("MicroStrategy Certified Architect", "MicroStrategy Certified Architect", "CERTIFICATION"),
    ]
    
    # Combine all examples
    all_examples = (
        title_examples + 
        company_examples + 
        date_examples + 
        skill_examples + 
        education_examples + 
        cert_examples
    )
    
    print(f"🎯 Generated {len(all_examples)} training examples")
    
    # Validate and create training data
    TRAIN_DATA = []
    skipped_list = []
    
    for text, entity_text, label in all_examples:
        result, error = make_example(text, entity_text, label)
        if result:
            TRAIN_DATA.append(result)
        else:
            skipped_list.append((text, entity_text, label, error))
    
    print(f"✅ Valid examples: {len(TRAIN_DATA)}")
    print(f"❌ Skipped examples: {len(skipped_list)}")
    print(f"📊 Total: {len(all_examples)}")
    
    # Save expanded training data
    os.makedirs("training_data", exist_ok=True)
    
    with open("training_data/ner_train_expanded.json", "w", encoding="utf-8") as f:
        json.dump(TRAIN_DATA, f, indent=2, ensure_ascii=False)
    
    print(f"💾 Saved {len(TRAIN_DATA)} training examples to training_data/ner_train_expanded.json")
    
    if skipped_list:
        print(f"\n⚠️  First 10 skipped items:")
        for text, ent, lbl, err in skipped_list[:10]:
            print(f"  [{lbl}] '{ent}' in '{text[:50]}...' → {err}")
    
    return len(TRAIN_DATA)

if __name__ == "__main__":
    valid_count = generate_expanded_ner_training()
    print(f"\n✅ TASK 2 COMPLETE: {valid_count} valid NER training samples generated")
    print(f"🎯 Target: 500+ samples, Achieved: {valid_count}")
