"""add_match_scores_table

Revision ID: 100cc75d6ae7
Revises: add_summary_manually_edited
Create Date: 2026-04-11 20:16:39.506502

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '100cc75d6ae7'
down_revision = 'add_summary_manually_edited'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidates', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'success', 'failed', name='candidate_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidates', 'consent_given',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidates', 'tenant_id',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidates', 'review_status',
               existing_type=postgresql.ENUM('pending', 'in_review', 'approved', 'rejected', name='review_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('certifications', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('certifications', 'issuing_organization',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('correction_patterns', 'count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('correction_patterns', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('correction_stats', 'correction_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('corrections', 'corrected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('parsing_jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'success', 'failed', name='parsing_job_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('revoked_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('revoked_tokens_jti_key'), 'revoked_tokens', type_='unique')
    op.alter_column('skill_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.alter_column('work_history', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_history', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'default'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'recruiter'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('skill_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('revoked_tokens_jti_key'), 'revoked_tokens', ['jti'])
    op.alter_column('revoked_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('parsing_jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'success', 'failed', name='parsing_job_status'),
               server_default=sa.text("'pending'::parsing_job_status"),
               existing_nullable=False)
    op.alter_column('corrections', 'corrected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('correction_stats', 'correction_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('correction_patterns', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('correction_patterns', 'count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('certifications', 'issuing_organization',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('certifications', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('candidates', 'review_status',
               existing_type=postgresql.ENUM('pending', 'in_review', 'approved', 'rejected', name='review_status'),
               server_default=sa.text("'pending'::review_status"),
               existing_nullable=False)
    op.alter_column('candidates', 'tenant_id',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'default'::character varying"),
               existing_nullable=False)
    op.alter_column('candidates', 'consent_given',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('candidates', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'success', 'failed', name='candidate_status'),
               server_default=sa.text("'pending'::candidate_status"),
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'])
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('api_keys', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'viewer'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
